import { retrieveContext } from "./retrieve.service.js";
import { generateAnswer } from "./generate.service.js";

/**
 * Handles the end-to-end question answering pipeline for the portfolio.
 * Retrieves context chunks matching the search query from Qdrant (falling back to an empty context on error),
 * and feeds the combined context and query to the GenAI model to construct a response.
 *
 * @param {string} query - The trimmed user query or question.
 * @param {Array<{role: string, content: string}>} [history=[]] - Optional conversation history.
 * @returns {Promise<string>} Resolves with the text response generated by the AI provider.
 */
export async function askPortfolio(query, history = []) {
  let contexts = [];
  try {
    contexts = await retrieveContext(query, 5);
  } catch (err) {
    console.error("[askPortfolio] Retrieval failed:", err.message);
    // Fall through with empty context — LLM will respond with what it knows from system prompt
  }

  return await generateAnswer(query, contexts, history);
}
